Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -22,22 +22,16 @@ jobs:
           sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
 
-      - name: Start SSH agent
-        uses: webfactory/ssh-agent@v0.5.4
-        with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
-          
+      - name: Install sshpass
+        run: sudo apt-get install -y sshpass
+
       - name: Test SSH Connection
         run: |
-            ssh -o StrictHostKeyChecking=no -p 2222 ${{ secrets.SSH_USERNAME }}@${{ secrets.IP }} "echo 'Connection successful!'"
-            
-      - name: Add Tailscale IP to known hosts
-        run: |
-          ssh-keyscan -v -H -p 2222 -H ${{ secrets.IP }} >> ~/.ssh/known_hosts || echo "Failed to retrieve key"
+          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 2222 ${{ secrets.SSH_USERNAME }}@${{ secrets.IP }} "echo 'Connection successful!'" || echo "SSH connection failed"
 
       - name: Deploy to Homelab Server
         run: |
-          ssh p 2222 ${{ secrets.SSH_USERNAME }}@${{ secrets.IP }} << 'EOF'
+          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -p 2222 -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.IP }} << 'EOF'
             cd blakeridgway
             git pull origin main
             docker-compose down
